---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-apps
  namespace: default
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: default
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/luispabon/argocd-test.git
        revision: HEAD
        directories:
          - path: gitops/localdev/

  template:
    metadata:
      name: '{{.cluster}}-apps'
    spec:
      project: argocd-apps
      source:
        repoURL: https://github.com/luispabon/argocd-test.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
