apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - cluster: local
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{.cluster}}-apps'
    spec:
      project: argocd-test
      source:
        repoURL: https://github.com/luispabon/argocd-test.git
        targetRevision: HEAD
        path: gitops/{{.cluster}}
      destination:
        server: '{{.url}}'
